# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    # name: deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: deploy
      uses: appleboy/scp-action@master
      with:
        host: https://nenadbursac.com
        username: nenadbur
        # port: ${{ secrets.PORT }}
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA+fDPSliAtehTfr4lU+QcH+zuYWjqr/RWyBBkxJWYox0sM0/nNNTbc56GXrfzvOIJGzeWmMVdIseByBXOK2wuEVlo9c8ybvCaYn17mfKdQkiLH6WPn5y3VKACeZ3bZ7NnSXjeqbtbYjqx0fqO9DpfGKXJYIlFkjwwSiTXVwkhNhh1TglQcTjEqF/MdvET5V+NkharROpVdeh86BwXPh/4Mz5IeJBIvGqcbQHYEfo1C+OUnEb+SJSR0uesCaLMmaRNmc9Mr1wHXu8J3vnJCaOu5CF4Pmb/+Qe10ktuItN+x3mp2iouV0bcHp8uktAqaaMMylIwLFV1g2Cq6XMwuBXtiLvukHTASDMIxByHx7YMMjj1zttaXTKFbnZdwLlwgw7HqbYkLDPjSs0qTJVAJ1/x7fXskufPlZZHIlt5iVGh1w+Z4LfSPFe6WlfFxnSmLmH3tDJZCY9QWgpZmttIIvZkRTSTVcz099MiQ26zJ+4L/a2MiGEUZP739vr1cjWO5+0= nenad@HP-ENVY-UBT
        source: 'dist'
        target: 'test'
